### ISSUE TITLE
Do not ship test code in PyPI packages

### ISSUE THREAD

**Issue by pombredanne** [kojiromike/parameter-expansion#18]
Do not ship test code in PyPI packages as it makes the wheels and sdist bigger and serves no purpose as tests will unlikely ever be used in this form. The simple resolution is to move tests to their own top-level directory 

(and IMHO the sources should be in their own src/ top level too, as explained in the forever excellent post by @ionelmc at https://blog.ionelmc.ro/2014/05/25/python-packaging/ but that's another issue)

**Comment by kojiromike** [comment]
> Do not ship test code…

I actually do see value in shipping test code. (In fact, I keep thinking this repo might be a good candidate for doctests.) But I also understand the value of a smaller package, so as long as people can get the test code from the repo it's OK to move the tests out of the package.

> …src top level…

In principle I agree with this, and have always used `src` layout with setuptools packaging. Here I decided to follow the simplest possible layout according to poetry conventions. It's certainly possible to use a `src` layout with poetry, but I am not convinced it's worth it.
