### ISSUE TITLE
Can you make me a PyPI releaser?

### ISSUE THREAD

**Issue by pombredanne** [kojiromike/parameter-expansion#35]
Otherwise, I can continue to maintain a fork at https://pypi.org/project/parameter-expansion-patched/ ... but this does not make sense.
Note that automating this is not as important as being able to publish a release

**Comment by pombredanne** [comment]
well, short of having PyPI release rights, I have to maintain a released fork for now.
Please ping me here when you have a minute

**Comment by pombredanne** [comment]
gentle ping

**Comment by pombredanne** [comment]
gentle ping. I will maintain my fork otherwise

**Comment by jayvdb** [comment]
ping @kojiromike

**Comment by kojiromike** [comment]
@pombredanne invite sent. I had sent you an invite before, but it expired.

**Comment by pombredanne** [comment]
Thanks! accepted.
