### ISSUE TITLE
Add a few simple non-POSIX bash'isms

### ISSUE THREAD

**Issue by pombredanne** [kojiromike/parameter-expansion#8]
Some common bash'ism (non-POSIX) include substrings such as `${foo:4:2}` and replacement as in `${foo/bar/baz}`
I have a PR in the works. Would you be open to include these?

**Comment by pombredanne** [comment]
I pushed https://github.com/kojiromike/parameter-expansion/pull/9 for your review

**Comment by kojiromike** [comment]
Thanks, awesome! 

I've enabled the actions. I'll try to take a closer look at the code today.

**Comment by pombredanne** [comment]
Thanks! And FWIW, this will be used to support https://github.com/nexB/purldb/issues/307 and in particular https://github.com/nexB/purldb/issues/307 but also in the future a lightweight parsing and eval of various shell-based package manifests beyond Alpine Linux (e.g. Arch, Gentoo, MSYS2 and also autotools and a few more)

**Comment by pombredanne** [comment]
Fixed with the merger of nexB/scancode.io#9

**Comment by kojiromike** [comment]
I haven't finished automating deployment to pypi, so I'll do a manual one at some point.

**Comment by kojiromike** [comment]
0.2.0 wheel and sdist are on pypi. Please let me know how they work for you.
